// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package banners

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Banner struct {
	ID        int32
	CreatedAt pgtype.Timestamp
	IsActive  pgtype.Bool
	FeatureID int32
}

type BannersInfo struct {
	BannerID  pgtype.Int4
	UpdatedAt pgtype.Timestamp
	Contents  []byte
}

type BannersTag struct {
	BannerID pgtype.Int4
	TagID    pgtype.Int4
}
