// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package banners

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Banner struct {
	ID        int64
	FeatureID int32
	IsActive  bool
	CreatedAt pgtype.Timestamp
}

type BannersInfo struct {
	BannerID  pgtype.Int4
	Contents  []byte
	UpdatedAt pgtype.Timestamp
}

type BannersTag struct {
	BannerID pgtype.Int4
	TagID    pgtype.Int4
}
