version: "3.1"
services:
  db:
    image: postgres:16.2-alpine3.19
    hostname: ff-db
    container_name: ff-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  banners:
    build: .
    container_name: bannersService
    hostname: banners
    ports:
      - "8080:8080"
    depends_on:
      - db