env: "local" # local, dev, prod
dsn: "postgresql://postgres:password@localhost:5432/postgres"
auth:
  private_key: "secret_key"
  expiration_time: "10m"
cache:
  expiration_time: "1m"
  redis_addr: "redis:6379"
http_server:
  address: "0.0.0.0:8080"
  timeout: "4s"
  idle_timeout: "60s"